site_name: Akshata — Technical Writing Portfolio
site_description: Selected technical writing samples.
repo_url: https://github.com/YOUR-USERNAME/tw-portfolio
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Montserrat          # body text (UI + headings are overridden via CSS)
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.tabs         # keep horizontal navigation
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: "2-4"
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - UI & Feature documentation:
      - UI & Feature documentation samples: ui-feature/index.md
      - (UI) Layout of the Conversation Details page: ui-feature/layout-of-the-conversation-details-page.md
      - (UI) Homepage Introduction: ui-feature/homepage-introduction.md
      - (Feature) AgentGPT: ui-feature/agentgpt.md


  - How-tos & FAQs:
      - How-to articles & Frequently Asked Questions (FAQs) samples: how-tos-faqs/index.md
      - How to find conversations in the platform? : how-tos-faqs/how-to-find-conversations-in-the-platform.md
      - FAQs for Agents and Managers: how-tos-faqs/faq-agents-managers.md

  - API & Integration documentation:
      - API & Integration documentation samples: api-integration/index.md
      - Nice inContact <> Instance Integration: api-integration/integration.md
  - Release notes:
      - Release Notes examples: release-notes/index.md

  - Tech blogs:
      - Tech blogs examples: blogs/index.md
      - "Speech to Text": blogs/speech-to-text-1.md
      - "How Speech-to-Text Transciption works": blogs/speech-to-text-2.md

  - Process tools:
      - Overview: process-tools/index.md
