site_name: Akshata — Technical Writing Portfolio
site_description: Selected technical writing samples.
repo_url: https://github.com/YOUR-USERNAME/tw-portfolio
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Montserrat          # body text (UI + headings are overridden via CSS)
    code: JetBrains Mono
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.tabs         # keep horizontal navigation
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.code.copy
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
      toc_depth: "2-4"
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  
  - UI & Feature docs:
      - UI & Feature documentation samples: ui-feature/index.md
      - UI:
        - Layout of the Conversation Details page: ui-feature/layout-of-the-conversation-details-page.md
        - Homepage Introduction: ui-feature/homepage-introduction.md
      - Feature:
        - AgentGPT: ui-feature/agentgpt.md


  - How-to's & FAQs:
      - How-to articles & Frequently Asked Questions (FAQs) samples: how-tos-faqs/index.md
      - How-to's:
        - How to find conversations in the platform? : how-tos-faqs/how-to-find-conversations-in-the-platform.md
      - FAQs:
        - FAQs for Agents and Managers: how-tos-faqs/faq-agents-managers.md

  - API & Integration docs:
    - API & Integration documentation samples: api-integration/index.md
    - APIs:
      - Group-image API: api-integration/api-air-1.md
      - Digital Asset Management:
        - Asset Management API: api-integration/api-am-1.md
        - Asset operations: api-integration/api-am-2.md
        - Updating an asset: api-integration/api-am-3.md
        - Restoring an expired asset: api-integration/api-am-4.md
        - Deleting an asset: api-integration/api-am-5.md
        - Reading and querying an asset: api-integration/api-am-6.md
    - Data Export:
      - Snowflake instance to SW3: api-integration/data-export.md
    - Integrations:
      - Nice inContact <> Instance Integration: api-integration/integration.md

  - Release notes:
      - Release Notes samples: release-notes/index.md
      - Release notes in CMS: release-notes/release-note-cms.md
      - Release announcements in-app: release-notes/release-note-app.md

  - Tech blogs:
      - Tech blogs samples: blogs/index.md
      - Speech to Text: blogs/speech-to-text-1.md
      - How Speech-to-Text Transciption works: blogs/speech-to-text-2.md

  - Training Guides:
    - Training guides examples: training-guides/index.md
    - Internal:
      - Image annotation training guide: training-guides/annotation.md
    - External:
      - AI prompts training guide: training-guides/ai-prompt.md
     

  - Process tools:
      - Tools I Use: process-tools/index.md
