name: Deploy MkDocs site
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs==1.6.1 mkdocs-material==9.6.20 pymdown-extensions
      - run: mkdocs gh-deploy --force
